#! /usr/bin/env bash

echo "== Delete Objects"

set -e

if [ -z "$1" ]; then
    echo "No Bucket Name Provided e.g. ./delete-objects my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects --bucket $BUCKET_NAME --query 'Contents[].Key' | jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete "$(cat /tmp/delete.json)"